---
title: "Threshold Assessment of Model Performance"
author: "Liam O'Suilleabhaiun"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Visualizing calibration}
  %\VignetteEngine{knitr::rmarkdown}
  \usepackage[utf8]{inputenc}
---

# This will be a vignette for the calibration plot examples

```{r}
library(gmish)
library(randomForest)

dd <- ggplot2::diamonds
dd$exp <- dd$price > 5000
dd$price <- NULL

m1 <- glm(exp ~ ., data = dd, family = 'binomial')
p1 <- predict(m1, type = 'response')

m2 <- randomForest(as.factor(exp) ~ ., data = dd, ntrees = 200)
p2 <- predict(m2, type = 'prob')[,2]

res <- data.frame(obs = dd$exp, glm = p1, rf = p2)
```

```{r threshstats, warning=FALSE, message=FALSE}
library(ggplot2)
y <- dd$exp; yhat <- p2

ts <- threshstats(preds=yhat,obs=y)

df <- data.frame(yhat=rev(yhat[ts$op[ts$np]]),
                 PPV=rev(ts$PPV), NNE=1/rev(ts$PPV),
                 sensitivity=rev(ts$sensitivity))
df <- df[-c((nrow(df)-125):nrow(df)),]
```

## Precision

```{r PPV_v_yhat, fig.height = 6, fig.width = 6, fig.align = "center"}
ggplot(df, aes(yhat, PPV)) +
  geom_line() + xlim(0, 1) + ylim(0, 1) +
  theme_bw() +
  coord_fixed()
```

## NNE

Number Needed to Evaluate one patient with outcome.

```{r NNE_v_yhat,fig.height = 6, fig.width = 6, fig.align = "center"}
ggplot(df, aes(yhat, NNE)) +
  geom_line() + xlim(0, 1) +
  theme_bw() 
```

## Sensitivity

```{r sensitivity_v_yhat, fig.height = 6, fig.width = 6, fig.align = "center"}
ggplot(df, aes(yhat, sensitivity)) +
  geom_line() + xlim(0, 1) + ylim(0, 1) +
  theme_bw() +
  coord_fixed()

```

## NNE vs Sensitivity

```{r NNE_v_sensitivity, fig.height = 6, fig.width = 6, fig.align = "center"}
ggplot(df, aes(sensitivity, NNE)) +
  geom_line() + xlim(0, 1) +
  theme_bw() 
```

